### ISSUE TITLE
Salesforce Assets are not bundled in the package [BUG]

### ISSUE THREAD

**Issue by AllanOricil** [marceloatg/vuetning#112]
Salesforce Ux package is not a dependency. Is there a reason? You could bundle it and when we import the components you could import the assets folder from the salesforce ux package.

**Comment by marceloatg** [comment]
Hi, this is by design. Vuetning was designed to work independently of SLDS library because we can use it directly in Salesforce, within a Visualforce for example. Because Salesforce already have SLDS internally there is no need to duplicate it. One bonus factor is that Vuetning becomes a little bit more resilient to updates in SLDS versions, and more flexible because one can build its own version of SLDS changing variables in the SCSS to achieve more customization.

Here's an example of usage using npm:

```<!DOCTYPE html>
<html>
<head>
  <link href="https://cdn.jsdelivr.net/npm/@salesforce-ux/design-system/assets/styles/salesforce-lightning-design-system.min.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
</head>
<body>
  <div id="app">
    <slds-button brand label="Hello World"/>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vuetning/dist/vuetning.umd.min.js"></script>
  <script>
    new Vue({
      el: '#app'
    })
  </script>
</body>
</html>```

**Comment by AllanOricil** [comment]
It does make sense now. Great job!
