### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pgrantmartello** [marceloatg/vuetning#137]
**Describe the bug**
If a form element is `readOnly`, the label should be replaced with a span. Consider

```
<component :is="readOnly ? 'span' : 'label'" class="slds-form-element__label">
```

**Additional context**
https://lightningdesignsystem.com/components/form-element/#View-ModeStatic

**Comment by marceloatg** [comment]
Hi, thank you @pgrantmartello for reporting this issue, I'll handle it ass soon as I can.

**Comment by AllanOricil** [comment]
Their doc is kind mess. Look at the below example of an input field that is readOnly. 

https://www.lightningdesignsystem.com/components/input/#Read-Only

They are still using label and not span.

**Comment by marceloatg** [comment]
@AllanOricil yes, I agree. One nice thing is that I found the [Salesforce Base Components Recipes](https://github.com/salesforce/base-components-recipes) repository. I started working on the vue.js 3 version of vuetning, following the LWC components because LWC and Vue are pretty similar, so I'll refactor the vuetning for vue.js 2 as well following more closely the LWC instead of the pure SLDS, which is confusing and inconsistent.

**Comment by marceloatg** [comment]
@pgrantmartello I'm closing this issue because as pointed by @AllanOricil the documentation for the **input** component uses label instead of span, like the documentation for Form element, which is a more generic documentation.

Thanks guys for helping me out!
