### ISSUE TITLE
[FEATURE] Vue3 support?

### ISSUE THREAD

**Issue by PhyberApex** [marceloatg/vuetning#196]
Did you think about Vue3 support already?

**Comment by marceloatg** [comment]
Hi, yes, but the problem is that vuetning is being created to support another private project, so since I'm working on it anyways I decided to make it public, and this project needs a feature from vue 2 that vue 3 does not support yet (there's this RFC that is opened for over 2 years https://github.com/vuejs/rfcs/discussions/283).

So, to answer your question, while this other project cannot be converted to Vue 3, I'll not create a vue 3 version of vuetning.
